// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvfqqayqacwecvnetbry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2ZnFxYXlxYWN3ZWN2bmV0YnJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNjEzNTEsImV4cCI6MjA2MzczNzM1MX0.g1NONnVU1-Yid8vVjwyOpHNQSrEfbl1ZQP9bjPIWVwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);